"""
convert_fall_to_dart.py
=======================
Converts the trained fall detection model (fall_model.pkl) to a Dart function
using m2cgen, then wraps it so AccelBuffer.extractAndSlide() output can be
passed directly.

Usage
-----
  cd cardiva_ml_models
  pip install -r requirements.txt
  python convert_fall_to_dart.py

Output
------
  ../lib/engine/generated/fall_model_generated.dart

The generated file exports:
  double fallModelScore(List<dynamic> input)

  Returns 1.0 = Fall, 0.0 = Not Fall.
  Input must be the 70-element feature vector from AccelBuffer.extractAndSlide().

Notes
-----
- LightGBM and RandomForest are both supported by m2cgen.
- For LightGBM, install lightgbm: `pip install lightgbm`
- For RandomForest (sklearn) no extra install needed.
- The trained pkl may be a bundle dict ({'model': ..., 'feature_cols': ...,
  'window_size': ..., 'step_size': ..., 'label_names': ...}) rather than a bare
  estimator — this script unwraps that automatically.
"""

import pickle
import sys
import threading
import m2cgen as m2c
import numpy as np

MODEL_PATH  = "fall_model.pkl"
OUTPUT_PATH = "../lib/engine/generated/fall_model_generated.dart"

# ── Load model ────────────────────────────────────────────────────────────────
with open(MODEL_PATH, "rb") as f:
    loaded = pickle.load(f)

bundle_meta = loaded if isinstance(loaded, dict) else {}
model = bundle_meta.get("model", loaded)

print(f"Loaded model: {type(model).__name__}")
if bundle_meta:
    print(f"  Bundle keys: {list(bundle_meta.keys())}")
    print(f"  feature_cols: {len(bundle_meta.get('feature_cols', []))} features")
    print(f"  window_size={bundle_meta.get('window_size')}  step_size={bundle_meta.get('step_size')}")
    print(f"  label_names: {bundle_meta.get('label_names')}")

n_features = len(bundle_meta.get("feature_cols", [])) or 70

# ── Export to raw Dart via m2cgen ─────────────────────────────────────────────
# Large tree ensembles (500 trees x depth 8 here) blow Python's default recursion
# limit inside m2cgen's AST interpreter. Run it on a thread with a bigger stack
# and a raised recursion limit to avoid RecursionError.
_export_result = {}


def _do_export():
    sys.setrecursionlimit(1_000_000)
    _export_result["dart"] = m2c.export_to_dart(model, function_name="__fallModelInternal")


threading.stack_size(64 * 1024 * 1024)  # 64MB
_export_thread = threading.Thread(target=_do_export)
_export_thread.start()
_export_thread.join()

if "dart" not in _export_result:
    print("ERROR: m2cgen export failed (see traceback above).")
    sys.exit(1)

raw_dart = _export_result["dart"]

# ── Determine class ordering ──────────────────────────────────────────────────
# m2cgen returns a List<double> for multi-class or a single double for binary.
# Prefer the bundle's own label_names/fall_label (authoritative, from training)
# and fall back to scanning classes_ by name if the bundle doesn't have them.
classes = getattr(model, "classes_", None)
fall_class_idx = 1   # default: assume class 1 = Fall

label_names = bundle_meta.get("label_names")
fall_label = bundle_meta.get("fall_label")
if label_names is not None and fall_label is not None and classes is not None:
    fall_class_idx = list(classes).index(fall_label)
    print(f"  Using bundle label_names={label_names}, fall_label={fall_label} -> class index {fall_class_idx}")
elif classes is not None:
    cls_list = [str(c).lower() for c in classes]
    print(f"  classes_: {list(classes)}")
    for i, c in enumerate(cls_list):
        if "fall" in c and "no" not in c and "not" not in c:
            fall_class_idx = i
            break
    print(f"  Using class index {fall_class_idx} as Fall positive")

# ── Hoist any imports (e.g. `import 'dart:math';` for LightGBM's exp()) ───────
# Dart requires import directives before any other declaration, but raw_dart is
# spliced in after the wrapper function, so pull them out and put them up top.
raw_dart_lines = raw_dart.splitlines()
import_lines = [l for l in raw_dart_lines if l.strip().startswith("import ")]
raw_dart_body = "\n".join(l for l in raw_dart_lines if not l.strip().startswith("import "))
imports_block = "\n".join(import_lines)

# ── Build wrapper ─────────────────────────────────────────────────────────────
wrapper = f"""{imports_block}
/// Auto-generated by convert_fall_to_dart.py — DO NOT EDIT.
///
/// Model : {type(model).__name__} (Fall_Detection.py, v{bundle_meta.get('version', '?')})
/// Input : {n_features}-element feature vector from AccelBuffer.extractAndSlide()
///         NOT vitals — pure accelerometer window ({bundle_meta.get('window_size', 100)} samples,
///         step {bundle_meta.get('step_size', 50)}).
///
/// Returns : 1.0 → Fall  |  0.0 → Not Fall
///
/// To regenerate:
///   1. Train model in Colab (Fall_Detection.py) → download fall_model.pkl
///   2. Place fall_model.pkl in cardiva_ml_models/
///   3. cd cardiva_ml_models && python convert_fall_to_dart.py

// ignore_for_file: unused_local_variable, non_constant_identifier_names, unnecessary_type_check

double fallModelScore(List<dynamic> input) {{
  if (input.length < {n_features}) return 0.0;
  final x = input.map((e) => (e as num).toDouble()).toList();
  final raw = __fallModelInternal(x);
  // raw is List<double> (multi-class) or double (binary)
  double score;
  if (raw is List) {{
    score = (raw[{fall_class_idx}] as num).toDouble();
  }} else {{
    score = (raw as num).toDouble();
  }}
  return score;
}}

{raw_dart_body}
"""

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(wrapper)

print(f"\nWritten to {OUTPUT_PATH}")
print("Now run: flutter analyze lib/engine/generated/fall_model_generated.dart")
