"""
convert_fall_to_dart.py
=======================
Converts the trained fall detection model (fall_model.pkl) to a Dart function
using m2cgen, then wraps it so AccelBuffer.extractAndSlide() output can be
passed directly.

Usage
-----
  cd cardiva_ml_models
  pip install -r requirements.txt
  python convert_fall_to_dart.py

Output
------
  ../lib/engine/generated/fall_model_generated.dart

The generated file exports:
  double fallModelScore(List<dynamic> input)

  Returns 1.0 = Fall, 0.0 = Not Fall.
  Input must be the 70-element feature vector from AccelBuffer.extractAndSlide().

Notes
-----
- LightGBM and RandomForest are both supported by m2cgen.
- For LightGBM, install lightgbm: `pip install lightgbm`
- For RandomForest (sklearn) no extra install needed.
"""

import pickle
import m2cgen as m2c
import numpy as np

MODEL_PATH  = "fall_model.pkl"
OUTPUT_PATH = "../lib/engine/generated/fall_model_generated.dart"

# ── Load model ────────────────────────────────────────────────────────────────
with open(MODEL_PATH, "rb") as f:
    model = pickle.load(f)

print(f"Loaded model: {type(model).__name__}")

# ── Export to raw Dart via m2cgen ─────────────────────────────────────────────
raw_dart = m2c.export_to_dart(model, function_name="__fallModelInternal")

# ── Determine class ordering ──────────────────────────────────────────────────
# m2cgen returns a List<double> for multi-class or a single double for binary.
# sklearn GBC/RF with two classes uses alphabetical ordering.
# Typical labels after LabelEncoder: 0=Not Fall, 1=Fall (or "Fall"/"No Fall").
# We inspect classes_ to figure out which index is "fall positive".
classes = getattr(model, "classes_", None)
fall_class_idx = 1   # default: assume class 1 = Fall

if classes is not None:
    cls_list = [str(c).lower() for c in classes]
    print(f"  classes_: {list(classes)}")
    for i, c in enumerate(cls_list):
        if "fall" in c and "no" not in c and "not" not in c:
            fall_class_idx = i
            break
    print(f"  Using class index {fall_class_idx} as Fall positive")

# ── Build wrapper ─────────────────────────────────────────────────────────────
wrapper = f"""
/// Auto-generated by convert_fall_to_dart.py — DO NOT EDIT.
///
/// Model : {type(model).__name__} (Fall_Detection.py)
/// Input : 70-element feature vector from AccelBuffer.extractAndSlide()
///         NOT vitals — pure accelerometer window (100 samples, step 50).
///
/// Returns : 1.0 → Fall  |  0.0 → Not Fall
///
/// To regenerate:
///   1. Train model in Colab (Fall_Detection.py) → download fall_model.pkl
///   2. Place fall_model.pkl in cardiva_ml_models/
///   3. cd cardiva_ml_models && python convert_fall_to_dart.py

// ignore_for_file: unused_local_variable, non_constant_identifier_names

double fallModelScore(List<dynamic> input) {{
  if (input.length < 70) return 0.0;
  final raw = __fallModelInternal(input);
  // raw is List<double> (multi-class) or double (binary)
  double score;
  if (raw is List) {{
    score = (raw[{fall_class_idx}] as num).toDouble();
  }} else {{
    score = (raw as num).toDouble();
  }}
  return score;
}}

{raw_dart}
"""

with open(OUTPUT_PATH, "w") as f:
    f.write(wrapper)

print(f"\nWritten to {OUTPUT_PATH}")
print("Now run: flutter analyze lib/engine/generated/fall_model_generated.dart")
