"""
Cardiva ML Model → Dart Converter
==================================
Converts vitals_model.pkl (GradientBoostingClassifier trained in fyp_dataset1.py)
to a Dart function using m2cgen, then wraps it for ml_service.dart.

Usage:
  1. Put vitals_model.pkl in this folder (downloaded from Colab)
  2. pip install m2cgen scikit-learn numpy
  3. python convert_to_dart.py
  → Writes ../lib/engine/generated/emergency_model_generated.dart
"""

import pickle
import os
import sys

try:
    import m2cgen as m2c
except ImportError:
    print("ERROR: m2cgen not installed. Run:  pip install m2cgen scikit-learn numpy")
    sys.exit(1)

PKL_PATH    = "vitals_model.pkl"
OUTPUT_PATH = os.path.join("..", "lib", "engine", "generated", "emergency_model_generated.dart")

# Feature order MUST match training in fyp_dataset1.py:
#   feature_cols = ['Heart Rate', 'HRV', 'Respiratory Rate', 'Oxygen Saturation',
#                   'Age', 'Height (m)', 'Weight (kg)', 'Gender', 'BMI']
FEATURES = [
    "Heart Rate",         # 0  — bpm
    "HRV",                # 1  — ms (SDNN)
    "Respiratory Rate",   # 2  — breaths/min
    "Oxygen Saturation",  # 3  — % SpO2
    "Age",                # 4  — years
    "Height (m)",         # 5  — metres
    "Weight (kg)",        # 6  — kg
    "Gender",             # 7  — 0=Male, 1=Female (matches df['Gender'].map())
    "BMI",                # 8  — kg/m²
]

# ── Load ──────────────────────────────────────────────────────────────────────
if not os.path.exists(PKL_PATH):
    print(f"ERROR: '{PKL_PATH}' not found in this folder.")
    print("  → Download vitals_model.pkl from your Colab run and place it here.")
    sys.exit(1)

model = pickle.load(open(PKL_PATH, "rb"))
print(f"Model loaded. Type: {type(model).__name__}")
print(f"Classes: {model.classes_}")
print(f"n_estimators: {model.n_estimators}")

# ── Convert via m2cgen ────────────────────────────────────────────────────────
print("Converting to Dart with m2cgen...")
dart_body = m2c.export_to_dart(model, function_name="_riskModelScore")

# ── Figure out High Risk class index ─────────────────────────────────────────
classes = list(model.classes_)
print(f"class ordering: {classes}")

# sklearn sorts classes alphabetically: 'High Risk' < 'Low Risk'
# so class 0 = 'High Risk', class 1 = 'Low Risk'
high_risk_idx = classes.index("High Risk") if "High Risk" in classes else 0

# m2cgen for binary GBC returns a List<double> [score_class0, score_class1]
# or sometimes a single double (raw decision value, positive → class 1).
# We handle both cases in the wrapper.
if high_risk_idx == 0:
    score_logic = (
        "  // m2cgen output: List → compare scores; double → negative = class 0 (High Risk)\n"
        "  final raw = _riskModelScore(input);\n"
        "  if (raw is List) {\n"
        "    final s = raw.cast<num>();\n"
        "    return s[0] > s[1] ? 1.0 : 0.0;   // class 0 wins → High Risk\n"
        "  }\n"
        "  return (raw as double) < 0 ? 1.0 : 0.0;"
    )
else:
    score_logic = (
        "  final raw = _riskModelScore(input);\n"
        "  if (raw is List) {\n"
        "    final s = raw.cast<num>();\n"
        "    return s[1] > s[0] ? 1.0 : 0.0;\n"
        "  }\n"
        "  return (raw as double) > 0 ? 1.0 : 0.0;"
    )

# Print feature importances for info
feat_imp = sorted(zip(FEATURES, model.feature_importances_), key=lambda x: -x[1])
imp_lines = "\n".join(f"//   {f:<25} {i:.4f}" for f, i in feat_imp)

# ── Build final Dart file ─────────────────────────────────────────────────────
feature_doc = "\n".join(f"//   [{i}] {f}" for i, f in enumerate(FEATURES))

header = f"""// AUTO-GENERATED by cardiva_ml_models/convert_to_dart.py — do not edit by hand.
// Model   : GradientBoostingClassifier  (n_estimators={model.n_estimators})
// Classes : {classes}
// Dataset : human_vital_signs_dataset_2024.csv (fyp_dataset1.py)
//
// Feature order (index must match ml_service.dart):
{feature_doc}
//
// Feature importances:
{imp_lines}
//
// Returns : 1.0 → High Risk (maps to vitalsHighRisk=true in ml_service.dart)
//           0.0 → Low Risk  (normal)

// ignore_for_file: unused_local_variable, prefer_final_locals, unnecessary_type_check

"""

wrapper = f"""
/// Classifies patient vitals as High Risk (1.0) or Low Risk (0.0).
///
/// Input MUST be a 9-element list in training order:
///   [HR, HRV, RR, SpO2, Age, Height_m, Weight_kg, Gender(0/1), BMI]
double emergencyModelScore(List<dynamic> input) {{
{score_logic}
}}

"""

output = header + wrapper + dart_body

os.makedirs(os.path.dirname(os.path.abspath(OUTPUT_PATH)), exist_ok=True)
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(output)

print(f"\n✅  Written to:  {os.path.abspath(OUTPUT_PATH)}")
print(f"    Classes:     {classes}")
print(f"\n    Top features by importance:")
for feat, imp in feat_imp[:4]:
    print(f"      {feat:<25}  {imp:.4f}")
print("\nDone — rebuild the Flutter app to pick up the new model.")
